name: Build Mealie (custom pwa theme)

on:
  schedule:
    - cron: '0 0 * * 2'
  workflow_dispatch:

env:
  IMAGE_NAME: custom-pwa-mealie
  THEME_COLOR: "DDBF86"

jobs:
  check:
    name: Check for image update
    runs-on: ubuntu-latest
    outputs:
      update_image: ${{ steps.set_output.outputs.update }}
      latest_version: ${{ steps.latest.outputs.LATEST_OUTPUT }}
      last_version: ${{ steps.last.outputs.LAST_OUTPUT }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Get latest Mealie release
        id: latest
        run: |
          LATEST=$(curl -s https://api.github.com/repos/mealie-recipes/mealie/releases/latest \
            | jq -r '.tag_name')
          echo "LATEST=$LATEST" >> $GITHUB_ENV
          echo "LATEST_OUTPUT=$LATEST" >> $GITHUB_OUTPUT

      - name: Read last built version
        id: last
        run: |
          LAST=$(cat LAST_BUILT_VERSION)
          echo "LAST=$LAST" >> $GITHUB_ENV
          echo "LAST_OUTPUT=$LAST" >> $GITHUB_OUTPUT

      - name: Skip if no new version
        id: set_output
        if: env.LATEST == env.LAST
        run: |
          echo "No new Mealie release. Skipping build."
          echo "update=false" >> $GITHUB_OUTPUT
          exit 0

  build:
    name: Build new image
    needs: [check]
    if: needs.check.outputs.update_image != 'false'
    runs-on: ubuntu-latest
    env:
      LATEST: ${{ needs.check.outputs.latest_version }}
      LAST: ${{ needs.check.outputs.last_version }}
    steps:

      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Clone Mealie and patch color
        run: |
          git clone https://github.com/mealie-recipes/mealie.git
          cd mealie
          git checkout $LATEST
          sed -i -E "s/E58325/$THEME_COLOR/" ./frontend/nuxt.config.ts

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push image
        run: |
          cd mealie
          cp docker/Dockerfile .
          docker build \
            --platform linux/amd64 \
            --label org.opencontainers.image.version=$LATEST \
            -t ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$LATEST \
            -t ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest \
            .
          docker push --all-tags ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME

      - name: Store built version
        run: |
          echo "$LATEST" > LAST_BUILT_VERSION
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add LAST_BUILT_VERSION
          git commit -m "Built custom pwa Mealie $LATEST"
          git push
